services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.0
    command:
      - start-dev
      - --verbose
      - --import-realm
      - --features=oid4vc-vci
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info,de.arbeitsagentur:debug
      KC_HOSTNAME: ${KC_HOSTNAME:-}
      KC_PROXY_HEADERS: ${KC_PROXY_HEADERS:-}
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak-oid4vp/target/providers:/opt/keycloak/providers:ro
      - ./demo-app/config/keycloak:/opt/keycloak/data/import
      - ./sandbox:/opt/keycloak/sandbox:ro
