{{- if .Values.wallet.files.sandboxCert }}
apiVersion: v1
kind: Secret
metadata:
  name: wallet-demo-sandbox-cert
  labels:
    app: wallet-demo
type: Opaque
stringData:
  sandbox-combined.pem: |
{{ .Values.wallet.files.sandboxCert | indent 4 }}
{{- end }}
