{{- if .Values.wallet.files.sandboxVerifierInfo }}
apiVersion: v1
kind: Secret
metadata:
  name: wallet-demo-sandbox-verifier-info
  labels:
    app: wallet-demo
type: Opaque
stringData:
  sandbox-verifier-info.json: |
{{ .Values.wallet.files.sandboxVerifierInfo | indent 4 }}
{{- end }}
