apiVersion: v1
kind: Secret
metadata:
  name: wallet-demo-wallet-keys
  labels:
    app: wallet-demo
    app.kubernetes.io/component: wallet
type: Opaque
stringData:
  wallet-keys.json: |
{{ required "wallet.files.walletKeys is required" .Values.wallet.files.walletKeys | indent 4 }}
  verifier-keys.json: |
{{ required "wallet.files.verifierKeys is required" .Values.wallet.files.verifierKeys | indent 4 }}
  mock-issuer-keys.json: |
{{ required "wallet.files.mockIssuerKeys is required" .Values.wallet.files.mockIssuerKeys | indent 4 }}
{{- if .Values.wallet.files.sandboxCert }}
  sandbox-cert.pem: |
{{ .Values.wallet.files.sandboxCert | indent 4 }}
{{- end }}
{{- if .Values.wallet.files.sandboxVerifierInfo }}
  sandbox-verifier-info.json: |
{{ .Values.wallet.files.sandboxVerifierInfo | indent 4 }}
{{- end }}
