apiVersion: v1
kind: ConfigMap
metadata:
  name: wallet-demo-wallet-config
  labels:
    app: wallet-demo
    app.kubernetes.io/component: wallet
data:
  mock-issuer-configurations.json: |
{{ required "wallet.files.mockIssuerConfigurations is required" .Values.wallet.files.mockIssuerConfigurations | indent 4 }}
