name: Build and push image
on:
  push:
    tags: '**'
  workflow_dispatch: { }

jobs:
  build-and-push-image:
    # Run only for the ba-itsys organization
    if: github.repository_owner == 'ba-itsys'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Extract version from pom.xml'
        id: version
        run: echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT

      - name: 'Build and push wallet image'
        run: >
          mvn
          --batch-mode
          -pl demo-app
          -am
          -Dspring-boot.build-image.imageName=ghcr.io/${{ github.repository }}:${{ steps.version.outputs.version }}
          -Dspring-boot.build-image.publish=true
          -DskipTests
          package spring-boot:build-image

      - name: 'Build Keycloak provider'
        run: mvn --batch-mode -pl keycloak-oid4vp -am -DskipTests package

      - name: 'Build and push Keycloak image'
        uses: docker/build-push-action@v6
        with:
          context: keycloak-oid4vp
          push: true
          tags: ghcr.io/${{ github.repository }}-keycloak:${{ steps.version.outputs.version }}
