on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    # Run only for the ba-itsys organization
    if: github.repository_owner == 'ba-itsys'
    runs-on: ubuntu-latest
    steps:

      # Generate a token for the GitHub App
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.RELEASE_PLEASE_APP_ID }}
          private-key: ${{ secrets.RELEASE_PLEASE_APP_PRIVATE_KEY }}

      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          token: ${{ steps.app-token.outputs.token }}
          release-type: maven

      - uses: actions/checkout@v6
        if: |
          steps.release-please.outputs.prs_created == 'true' &&
          contains(fromJSON(steps.release-please.outputs.pr || '{}').labels, 'autorelease: snapshot')

      - name: Merge SNAPSHOT-PR automatically
        if: |
          steps.release-please.outputs.prs_created == 'true' &&
          contains(fromJSON(steps.release-please.outputs.pr || '{}').labels, 'autorelease: snapshot')
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          PR_NUMBER: ${{ fromJSON(steps.release-please.outputs.pr || '{}').number }}
        run: |
          echo "Merging PR $PR_NUMBER (SNAPSHOT)"
          gh pr merge --rebase --admin "$PR_NUMBER"
